# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-app-extention"
client_id = "36459abe50fa9070ab1de7dab4be0e53"
application_url = "https://yacht-drums-deposit-cook.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_files,read_themes"

[auth]
redirect_urls = [
  "https://yacht-drums-deposit-cook.trycloudflare.com/auth/callback",
  "https://yacht-drums-deposit-cook.trycloudflare.com/auth/shopify/callback",
  "https://yacht-drums-deposit-cook.trycloudflare.com/api/auth/callback",
  "https://yacht-drums-deposit-cook.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "teststore3222.myshopify.com"
